/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces.panels;

/**
 *
 * @author Jesus
 */
public class listaClientes extends javax.swing.JPanel {

    /**
     * Creates new form listaUsuarios
     */
    public listaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel10 = new javax.swing.JPanel();
        numero1 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        numero2 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        numero3 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        numero4 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        numero5 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        numero6 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 153, 153));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero1.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        numero1.setText("1.");
        jPanel10.add(numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 506, 60));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero2.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        numero2.setText("2.");
        jPanel8.add(numero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 506, 60));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero3.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        numero3.setText("6.");
        jPanel11.add(numero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 506, 60));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero4.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        numero4.setText("3.");
        jPanel15.add(numero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 506, 60));

        jPanel16.setBackground(new java.awt.Color(255, 255, 255));
        jPanel16.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero5.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        numero5.setText("4.");
        jPanel16.add(numero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        add(jPanel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 506, 60));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        numero6.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        numero6.setText("5.");
        jPanel17.add(numero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 24, -1, -1));

        add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 506, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel numero1;
    private javax.swing.JLabel numero2;
    private javax.swing.JLabel numero3;
    private javax.swing.JLabel numero4;
    private javax.swing.JLabel numero5;
    private javax.swing.JLabel numero6;
    // End of variables declaration//GEN-END:variables
}
