/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.charset.Charset;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import static java.nio.file.StandardCopyOption.REPLACE_EXISTING;
import static java.util.Locale.filter;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javapop.Cliente;
import javapop.Producto;
import static javapop.Variables.listaProductos;
import static javapop.Variables.usuario;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Jesus
 */
public class AddProducto extends javax.swing.JFrame {

    /**
     * Creates new form AddProducto
     */
    ImageIcon icon = new ImageIcon(".\\src\\javapop\\Imagenes\\uploadNormal.png");
    Image resizedImage = icon.getImage().getScaledInstance(320, 320, java.awt.Image.SCALE_DEFAULT);

    ImageIcon icon2 = new ImageIcon(".\\src\\javapop\\Imagenes\\UploadOver.png");
    Image resizedImage2 = icon2.getImage().getScaledInstance(320, 320, java.awt.Image.SCALE_DEFAULT);

    boolean fotoSubida = false;

    private FileNameExtensionFilter extension = new FileNameExtensionFilter("Archivo de imagen (*.jpg, *.jpeg, *.png, *.gif)", "jpg", "png", "jpeg", "gif");
    private String direccionImg;

    public AddProducto() {
        initComponents();

        uploadImg.setIcon(new ImageIcon(resizedImage));
        super.setIconImage(new ImageIcon("./javapop.Imagenes/LogoJavapop.png").getImage());
    }

    public static char randChar() {
        Random r = new Random();
        String alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUWXYZ0123456789";
        return alphabet.charAt(r.nextInt(alphabet.length()));
    }

    public static String nombreRandom(int len) {
        String nombre = "";
        for (int i = 0; i < len; i++) {
            nombre += randChar();
        }
        return nombre;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        categoria = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        uploadImg = new javax.swing.JLabel();
        precio = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        registrarse = new javax.swing.JButton();
        urgente = new javax.swing.JCheckBox();
        tituloError = new javax.swing.JLabel();
        precioError = new javax.swing.JLabel();
        descripcionError = new javax.swing.JLabel();
        fotoError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel1.setText("Título");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 34, 191, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel2.setText("Categoría");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel3.setText("Estado");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 188, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel5.setText("Descripción");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 247, -1, -1));

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nuevo", "Como nuevo", "Bueno", "Aceptable", "Regular" }));
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 191, 32));

        categoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Moda y accesorios", "TV", "audio y foto", "Móviles y telefonía", "Informática y electrónica", "Consolas y videojuegos", "Deporte y ocio", "" }));
        getContentPane().add(categoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 191, 32));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uploadImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapop/Imagenes/uploadNormal.png"))); // NOI18N
        uploadImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                uploadImgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                uploadImgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                uploadImgMouseExited(evt);
            }
        });
        jPanel1.add(uploadImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 320, 340));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 320, 320));

        precio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 30));

        descripcion.setColumns(20);
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 190, 100));

        registrarse.setBackground(new java.awt.Color(255, 125, 0));
        registrarse.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        registrarse.setForeground(new java.awt.Color(255, 255, 255));
        registrarse.setText("Subir producto");
        registrarse.setBorder(null);
        registrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                registrarseMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                registrarseMouseReleased(evt);
            }
        });
        registrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarseActionPerformed(evt);
            }
        });
        getContentPane().add(registrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 230, 30));

        urgente.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        urgente.setText("Urgente");
        getContentPane().add(urgente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        tituloError.setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().add(tituloError, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        precioError.setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().add(precioError, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        descripcionError.setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().add(descripcionError, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        fotoError.setForeground(new java.awt.Color(204, 51, 0));
        getContentPane().add(fotoError, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, -1, -1));

        setSize(new java.awt.Dimension(612, 485));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registrarseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMousePressed
        // TODO add your handling code here:
        Color naran = new Color(255, 160, 0);
        registrarse.setBackground(naran);
    }//GEN-LAST:event_registrarseMousePressed

    private void registrarseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrarseMouseReleased
        // TODO add your handling code here:

        Color naran = new Color(255, 125, 0);
        registrarse.setBackground(naran);
    }//GEN-LAST:event_registrarseMouseReleased


    private void uploadImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadImgMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(extension);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int i = fileChooser.showOpenDialog(this);
        if (i == JFileChooser.APPROVE_OPTION) {
            direccionImg = fileChooser.getSelectedFile().getPath();

            ImageIcon icon = new ImageIcon(this.direccionImg);
            Image resizedImage = icon.getImage().getScaledInstance(250, 250, java.awt.Image.SCALE_DEFAULT);
            uploadImg.setIcon(new ImageIcon(resizedImage));
            fotoSubida = true;
        }
    }//GEN-LAST:event_uploadImgMouseClicked

    private void registrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarseActionPerformed
        // TODO add your handling code here:  (String titulo, String categoria, String descripcion, String estadoProducto, String fotografia, String precio, Ubicacion ubicacion, Cliente cliente, boolean urgente)
        boolean correcto = true;
        tituloError.setText("");
        precioError.setText("");
        descripcionError.setText("");

        String titulop = titulo.getText();
        String categoriap = categoria.getItemAt(categoria.getSelectedIndex());
        String descripcionp = descripcion.getText();
        String estadop = estado.getItemAt(estado.getSelectedIndex());
        String preciop = precio.getText();
        boolean urgentep = urgente.isSelected();

        if (titulo.getText().isEmpty()) {
            tituloError.setText("Vacio");
            correcto = false;
        }
        if (precio.getText().isEmpty()) {
            precioError.setText("Vacio");
            correcto = false;
        }
        if (descripcion.getText().isEmpty()) {
            descripcionError.setText("Vacio");
            correcto = false;
        }
        if (!fotoSubida) {
            fotoError.setText("Cargue una imagen de su ordenador");
            correcto = false;
        }

        FileSystem fileSys = FileSystems.getDefault();
        File imgFolder = new File(".\\src\\javapop\\ImagenesProductos\\");
        File image = new File(direccionImg);
        String newAddress;
        boolean run = true;
        
        if (correcto) {
            while (run) {
                newAddress = ".\\src\\javapop\\ImagenesProductos\\" + nombreRandom(10) + "-" + image.getName();
                try {
                    Files.copy(fileSys.getPath(direccionImg), fileSys.getPath(newAddress), REPLACE_EXISTING);
                } catch (IOException ex) {
                    Logger.getLogger(AddProducto.class.getName()).log(Level.SEVERE, null, ex);
                    run = false;
                }
                this.direccionImg = newAddress;
                run = false;

            }
            Producto producto = new Producto(titulop,categoriap,descripcionp,estadop, direccionImg, preciop,((Cliente)usuario).getUbicacion(),((Cliente)usuario),urgentep);
            
            ((Cliente)usuario).añadirProducto(producto);
            
            this.dispose();
        }

        //(String titulo, String categoria, String descripcion, String estadoProducto, String fotografia, String precio, Ubicacion ubicacion, Cliente cliente, boolean urgente);

    }//GEN-LAST:event_registrarseActionPerformed

    private void uploadImgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadImgMouseEntered
        // TODO add your handling code here:
        if (!fotoSubida) {
            uploadImg.setIcon(new ImageIcon(resizedImage2));
        }
    }//GEN-LAST:event_uploadImgMouseEntered

    private void uploadImgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_uploadImgMouseExited
        // TODO add your handling code here:
        if (!fotoSubida) {
            uploadImg.setIcon(new ImageIcon(resizedImage));
        }
    }//GEN-LAST:event_uploadImgMouseExited

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddProducto().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> categoria;
    private javax.swing.JTextArea descripcion;
    private javax.swing.JLabel descripcionError;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JLabel fotoError;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField precio;
    private javax.swing.JLabel precioError;
    private javax.swing.JButton registrarse;
    private javax.swing.JTextField titulo;
    private javax.swing.JLabel tituloError;
    private javax.swing.JLabel uploadImg;
    private javax.swing.JCheckBox urgente;
    // End of variables declaration//GEN-END:variables
}
