/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Interfaces.panels.listaClientes;
import java.awt.Color;
import java.awt.Image;
import javapop.Cliente;
import javapop.Producto;
import static javapop.Variables.listaClientes;
import static javapop.Variables.listaProductos;
import static javapop.Variables.listaVentas;
import static javapop.Variables.usuario;
import javapop.Venta;
import javax.swing.ImageIcon;

/**
 *
 * @author Jesus
 */
public class CompraProducto extends javax.swing.JFrame {

    /**
     * Creates new form CompraProducto
     */
    Producto produc;
    public CompraProducto(Producto producto) {
        initComponents();
        produc = producto;
        
        rellenarDatosProducto(producto);
    }
    
    private void rellenarDatosProducto(Producto producto) {
        tituloInfo.setText(producto.getTitulo());
        categoriaInfo.setText(producto.getCategoria());
        estadoInfo.setText(producto.getEstadoProducto());
        precioInfo.setText(producto.getPrecio());
        descripcionInfo.setText(producto.getDescripcion());
        urgenteInfo.setSelected(producto.isUrgente());
        infopropietario.setText(producto.getCliente().getNombre());
        ImageIcon icon = new ImageIcon(producto.getFotografia());
        Image resizedImage = icon.getImage().getScaledInstance(280, 280, java.awt.Image.SCALE_DEFAULT);
        uploadImgInfo.setIcon(new ImageIcon(resizedImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        categoriaInfo = new javax.swing.JTextField();
        estadoInfo = new javax.swing.JTextField();
        urgenteInfo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionInfo = new javax.swing.JTextArea();
        precioInfo = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        uploadImgInfo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        infopropietario = new javax.swing.JLabel();
        botonComprar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        tituloInfo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categoriaInfo.setEditable(false);
        categoriaInfo.setBackground(new java.awt.Color(255, 255, 255));
        categoriaInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(categoriaInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 38, 191, 30));

        estadoInfo.setEditable(false);
        estadoInfo.setBackground(new java.awt.Color(255, 255, 255));
        estadoInfo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel3.add(estadoInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 114, 191, 30));

        urgenteInfo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        urgenteInfo.setText("Urgente");
        urgenteInfo.setEnabled(false);
        jPanel3.add(urgenteInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 190, -1));

        descripcionInfo.setEditable(false);
        descripcionInfo.setColumns(20);
        descripcionInfo.setRows(5);
        jScrollPane1.setViewportView(descripcionInfo);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 253, 190, 100));

        precioInfo.setEditable(false);
        precioInfo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel3.add(precioInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, 190, 30));

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 153, -1, -1));

        jLabel5.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel5.setText("Descripción");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, -1, -1));

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel4.setText("Precio");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 155, -1, -1));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel3.setText("Estado");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 79, -1, -1));

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 13)); // NOI18N
        jLabel2.setText("Categoría");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        uploadImgInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapop/Imagenes/uploadNormal.png"))); // NOI18N
        jPanel3.add(uploadImgInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 280, 280));

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("Propietario: ");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, 20));

        infopropietario.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jPanel3.add(infopropietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 220, 20));

        botonComprar.setBackground(new java.awt.Color(255, 125, 0));
        botonComprar.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        botonComprar.setForeground(new java.awt.Color(255, 255, 255));
        botonComprar.setText("Comprar");
        botonComprar.setBorder(null);
        botonComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                botonComprarMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                botonComprarMouseReleased(evt);
            }
        });
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });
        jPanel3.add(botonComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 430, 40));

        jPanel2.setBackground(new java.awt.Color(244, 184, 44));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloInfo.setEditable(false);
        tituloInfo.setBackground(new java.awt.Color(244, 184, 44));
        tituloInfo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        tituloInfo.setForeground(new java.awt.Color(255, 255, 255));
        tituloInfo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tituloInfo.setBorder(null);
        jPanel2.add(tituloInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 612, 68));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(638, 591));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botonComprarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComprarMousePressed
        // TODO add your handling code here:
        Color naran = new Color(255, 160, 0);
        botonComprar.setBackground(naran);
    }//GEN-LAST:event_botonComprarMousePressed

    private void botonComprarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonComprarMouseReleased
        // TODO add your handling code here:

        Color naran = new Color(255, 125, 0);
        botonComprar.setBackground(naran);
    }//GEN-LAST:event_botonComprarMouseReleased

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonComprarActionPerformed
        // TODO add your handling code here:
        
        Venta venta = new Venta(produc, (Cliente)usuario, produc.getCliente());
        int index = -1;
        
        for (Cliente cliente: listaClientes){
            if (cliente.getCorreo().equals(produc.getCliente().getCorreo())){
                index = listaClientes.indexOf(cliente);
            }
        }
        
        Cliente aux = produc.getCliente();
        
        aux.getListaProductos().remove(produc);
        
        
        listaClientes.set(index, aux);
        
        listaVentas.add(venta);
        
        listaProductos.remove(produc);
        
        
        this.dispose();
        
        
    }//GEN-LAST:event_botonComprarActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonComprar;
    private javax.swing.JTextField categoriaInfo;
    private javax.swing.JTextArea descripcionInfo;
    private javax.swing.JTextField estadoInfo;
    private javax.swing.JLabel infopropietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField precioInfo;
    private javax.swing.JTextField tituloInfo;
    private javax.swing.JLabel uploadImgInfo;
    private javax.swing.JCheckBox urgenteInfo;
    // End of variables declaration//GEN-END:variables
}
