/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import java.awt.Color;
import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.ArrayList;
import javapop.Admin;
import static javapop.Aplicacion.buscarCorreo;
import javapop.Cliente;
import javapop.ClienteProfesional;
import javapop.IOinfo;
import javapop.Producto;
import static javapop.Variables.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Jesús Palomino Abreu
 * @author Nicolás Moreno González
 *
 * @version v2.0 06/2019
 */
public class LoginP extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public LoginP() {

        initComponents();
        clave.setEchoChar((char) 0);
        super.setIconImage(new ImageIcon(".\\src\\javapop\\Imagenes\\LogoJavapop.png").getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginPanel = new javax.swing.JPanel();
        correo = new javax.swing.JTextField();
        clave = new javax.swing.JPasswordField();
        IniSesion = new javax.swing.JButton();
        errorCorreo = new javax.swing.JLabel();
        errorContra = new javax.swing.JLabel();
        NuevoJavaPop = new javax.swing.JLabel();
        registrate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javapop/Imagenes/LogoJavapop.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 216, 117));

        loginPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        correo.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        correo.setForeground(new java.awt.Color(153, 153, 153));
        correo.setText("Introduzca su correo");
        correo.setToolTipText("");
        correo.setSelectionColor(new java.awt.Color(255, 125, 0));
        correo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                correoFocusLost(evt);
            }
        });
        correo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                correoMouseClicked(evt);
            }
        });
        loginPanel.add(correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 283, 28));

        clave.setFont(new java.awt.Font("Verdana", 0, 15)); // NOI18N
        clave.setForeground(new java.awt.Color(153, 153, 153));
        clave.setText("Introduzca su contraseña");
        clave.setSelectionColor(new java.awt.Color(255, 125, 0));
        clave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                claveMouseClicked(evt);
            }
        });
        clave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claveActionPerformed(evt);
            }
        });
        loginPanel.add(clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 283, 29));

        IniSesion.setBackground(new java.awt.Color(255, 125, 0));
        IniSesion.setFont(new java.awt.Font("Verdana", 0, 17)); // NOI18N
        IniSesion.setForeground(new java.awt.Color(255, 255, 255));
        IniSesion.setText("Iniciar sesión");
        IniSesion.setBorder(null);
        IniSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        IniSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IniSesionMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                IniSesionMouseReleased(evt);
            }
        });
        IniSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IniSesionActionPerformed(evt);
            }
        });
        loginPanel.add(IniSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 283, 26));

        errorCorreo.setForeground(new java.awt.Color(255, 0, 0));
        loginPanel.add(errorCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 280, 20));

        errorContra.setForeground(new java.awt.Color(204, 0, 0));
        loginPanel.add(errorContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 230, 20));

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 230));

        NuevoJavaPop.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        NuevoJavaPop.setForeground(new java.awt.Color(102, 102, 102));
        NuevoJavaPop.setText("¿Nuevo en JavaPoP?");
        getContentPane().add(NuevoJavaPop, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 442, -1, -1));

        registrate.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        registrate.setForeground(new java.awt.Color(255, 125, 0));
        registrate.setText("Regístrate");
        registrate.setBorder(null);
        registrate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registrate.setOpaque(false);
        registrate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registrateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registrateMouseExited(evt);
            }
        });
        registrate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrateActionPerformed(evt);
            }
        });
        getContentPane().add(registrate, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 442, 98, -1));

        setSize(new java.awt.Dimension(418, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * <p>
     * Si se hace click se borra el contenido de la casilla y se cambia el color
     * del mensaje a negro</p>
     *
     * @param evt
     */
    private void correoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_correoMouseClicked
        // TODO add your handling code here:
        if (correo.getText().equals("Introduzca su correo")) {
            correo.setText("");
            correo.setForeground(Color.black);
        }
    }//GEN-LAST:event_correoMouseClicked


    private void claveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_claveActionPerformed

    /**
     * <p>
     * Si se hace click se borra el contenido de la casilla y se cambia el color
     * del mensaje a negro</p>
     *
     * @param evt
     */
    private void claveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claveMouseClicked
        // TODO add your handling code here:
        String pass = new String(clave.getPassword());
        if (pass.equals("Introduzca su contraseña")) {
            clave.setText("");
            clave.setForeground(Color.black);
            clave.setEchoChar('•');
        }
    }//GEN-LAST:event_claveMouseClicked

    /**
     * <p>
     * Si el usuario hace click le llevará a su ventana correspondiente
     * dependiendo de si es usuario normal, usuario profesional o
     * administrador</p>
     *
     * @param evt
     */
    private void IniSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IniSesionActionPerformed
        // TODO add your handling code here:

        try {
            errorContra.setText("");
            errorCorreo.setText("");
            String textCorreo = correo.getText();

            String textClave = new String(clave.getPassword());

            Object user = buscarCorreo(textCorreo);
            if (user instanceof ClienteProfesional) {
                usuario = user;
                if (textClave.equals(((ClienteProfesional) usuario).getClave())) {
                    new PagCliente().setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Ha iniciado sesión como Cliente Profesional.");

                } else {
                    errorContra.setText("La contraseña es incorrecta");

                }
            } else if (user instanceof Cliente) {
                usuario = user;
                if (textClave.equals(((Cliente) usuario).getClave())) {
                    new PagCliente().setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Ha iniciado sesión como Cliente.");

                } else {
                    errorContra.setText("La contraseña es incorrecta");

                }
            } else if (user instanceof Admin) {
                usuario = user;
                if (textClave.equals(((Admin) usuario).getClave())) {
                    new PagAdmin().setVisible(true);
                    this.dispose();
                    JOptionPane.showMessageDialog(this, "Ha iniciado sesión como Admin.");

                } else {
                    errorContra.setText("La contraseña es incorrecta");

                }
            } else {
                errorCorreo.setText("El correo no está asociado a ninguna cuenta de usuario");

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ha surgido un error: " + e.toString());

        }

    }//GEN-LAST:event_IniSesionActionPerformed

    private void IniSesionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniSesionMousePressed
        // TODO add your handling code here:
        Color naran = new Color(255, 160, 0);
        IniSesion.setBackground(naran);
    }//GEN-LAST:event_IniSesionMousePressed

    private void IniSesionMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IniSesionMouseReleased
        // TODO add your handling code here:

        Color naran = new Color(255, 125, 0);
        IniSesion.setBackground(naran);
    }//GEN-LAST:event_IniSesionMouseReleased

    private void correoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_correoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_correoFocusLost
    /**
     * <p>
     * Se guarda la informacion en un archivo cuando se cierra el programa</p>
     *
     * @param evt
     */
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

        IOinfo.guardarClientes(listaClientes);
        IOinfo.guardarProductos(listaProductos);
        IOinfo.guardarVentas(listaVentas);

        System.out.println("final programa" + listaVentas);
    }//GEN-LAST:event_formWindowClosing

    private void registrateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrateMouseEntered
        // TODO add your handling code here:
        registrate.setFont(new java.awt.Font("verdana", 1, 12));

    }//GEN-LAST:event_registrateMouseEntered
    /**
     * <p>
     * Si se hace click se abre la ventana Register y se cierra la de Login</p>
     *
     * @param evt
     */
    private void registrateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrateActionPerformed
        // TODO add your handling code here:
        new Register().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registrateActionPerformed

    private void registrateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registrateMouseExited
        // TODO add your handling code here:
        registrate.setFont(new java.awt.Font("verdana", 0, 12));
    }//GEN-LAST:event_registrateMouseExited

    /**
     * @param args the command line arguments
     */
    //public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */

 /*try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 /*java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginP().setVisible(true);

            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IniSesion;
    private javax.swing.JLabel NuevoJavaPop;
    private javax.swing.JPasswordField clave;
    private javax.swing.JTextField correo;
    private javax.swing.JLabel errorContra;
    private javax.swing.JLabel errorCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JButton registrate;
    // End of variables declaration//GEN-END:variables

}
